name: PISF
channels:
  - conda-forge
  - nvidia
  - pytorch
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - blas=1.0
  - bzip2=1.0.8
  - ca-certificates=2022.10.11
  - certifi=2021.5.30
  - cudatoolkit=11.3.1
  - cycler=0.11.0
  - dataclasses=0.8
  - dbus=1.13.18
  - expat=2.4.9
  - ffmpeg=4.3
  - fontconfig=2.13.1
  - freetype=2.12.1
  - glib=2.69.1
  - gmp=6.2.1
  - gnutls=3.6.15
  - gst-plugins-base=1.14.0
  - gstreamer=1.14.0
  - h5py=2.10.0
  - hdf5=1.10.6
  - icu=58.2
  - intel-openmp=2022.1.0
  - jpeg=9e
  - kiwisolver=1.3.1
  - lame=3.100
  - lcms2=2.12
  - ld_impl_linux-64=2.38
  - lerc=3.0
  - libdeflate=1.8
  - libffi=3.3
  - libgcc-ng=11.2.0
  - libgfortran-ng=7.5.0
  - libgfortran4=7.5.0
  - libgomp=11.2.0
  - libiconv=1.16
  - libidn2=2.3.2
  - libpng=1.6.37
  - libstdcxx-ng=11.2.0
  - libtasn1=4.16.0
  - libtiff=4.4.0
  - libunistring=0.9.10
  - libuuid=1.41.5
  - libuv=1.40.0
  - libwebp-base=1.2.4
  - libxcb=1.15
  - libxml2=2.9.14
  - lz4-c=1.9.3
  - matplotlib
  - matplotlib-base=3.3.4
  - mkl=2020.2
  - mkl-service=2.3.0
  - mkl_fft=1.3.0
  - mkl_random=1.1.1
  - ncurses=6.3
  - nettle=3.7.3
  - numpy=1.19.2
  - numpy-base=1.19.2
  - olefile=0.46
  - openh264=2.1.1
  - openjpeg=2.4.0
  - openssl=1.1.1s
  - pcre=8.45
  - pillow=8.3.1
  - pip=21.2.2
  - pyparsing=3.0.4
  - pyqt
  - python=3.6.13
  - python-dateutil=2.8.2
  - pytorch=1.10.1
  - pytorch-mutex=1.0
  - qt=5.9.7
  - readline=8.2
  - scipy=1.5.2
  - setuptools=58.0.4
  - sip=4.19.8
  - six=1.16.0
  - sqlite=3.40.0
  - tk=8.6.12
  - torchaudio=0.10.1
  - torchvision=0.11.2
  - tornado=6.1
  - typing_extensions=4.1.1
  - wheel=0.37.1
  - xz=5.2.6
  - zlib=1.2.13
  - zstd=1.5.2
